version: '3'
services:
  orientdb:
    image: orientdb:3.0.25
    container_name: "orientdb"
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: "rootpwd"
      ORIENTDB_OPTS_MEMORY: "-Xms1G -Xmx1G -Dstorage.diskCache.bufferSize=3000"
    volumes:
      - ../../../orientdb/databases:/orientdb/databases
      - ../../../orientdb/backup:/orientdb/backup
      - ../../../orientdb/config/orientdb-server-config.xml:/orientdb/config/orientdb-server-config.xml
